version: "3.9"
services:
  web:
    image: biwunor/student-tracker
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      uvicorn app.main:app
      --reload
      --host 0.0.0.0
      --port 8011
    ports:
      - "8011:8011"
    volumes:
      - ./:/app
    env_file:
      - .env
