{{- if and .Values.prometheusRules (hasKey .Values.prometheusRules "enabled") .Values.prometheusRules.enabled }}
{{- $fullname := (include "nativeseries.fullname" . | default .Release.Name) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{$fullname}}-alerts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nativeseries.labels" . | nindent 4 }}
    release: prometheus
    prometheus: kube-prometheus
    role: alert-rules
spec:
  groups:
  - name: {{$fullname}}-alerts
    rules:
    {{- range .Values.prometheusRules.rules }}
    - alert: {{ .alert }}
      expr: {{ .expr }}
      for: {{ .for }}
      labels:
        {{- toYaml .labels | nindent 8 }}
      annotations:
        {{- toYaml .annotations | nindent 8 }}
    {{- end }}
{{- end }}