{{- if .Values.secret.enabled }}
{{- $fullname := (include "nativeseries.fullname" . | default .Release.Name) }}
# API Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nativeseries.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}